---

# Exit if 'mongodb_minor_version' is not defined
- fail: msg="Can't Rollback MongoDB if 'mongodb_minor_version' is defined to 'latest' !"
  when: mongodb_minor_version =="latest"

# Rollback to MongoDB specific version
- name: MongoDB installation status
  shell: dpkg -s mongodb-org > /dev/null 2>&1
  register: mongodb_installation_status
  ignore_errors: yes
  changed_when: false

# if Return Code (rc) is not equal to zero, then MongoDB is not installed
- fail: msg="Can't Rollback MongoDB, since MongoDB is not installed !"
  when: mongodb_installation_status.rc != 0

- name: Rollback to specific MongoDB version (mongodb-org-server)
  apt: name=mongodb-org-server={{ mongodb_minor_version }} state=present force=yes
  when: mongodb_minor_version != "latest"

- name: Rollback to specific MongoDB version (mongodb-org-tools)
  apt: name=mongodb-org-tools={{ mongodb_minor_version }} state=present force=yes
  when: mongodb_minor_version != "latest"

- name: Rollback to specific MongoDB version (mongodb-org-shell)
  apt: name=mongodb-org-shell={{ mongodb_minor_version }} state=present force=yes
  when: mongodb_minor_version != "latest"

- name: Rollback to specific MongoDB version (mongodb-org-mongos)
  apt: name=mongodb-org-mongos={{ mongodb_minor_version }} state=present force=yes
  when: mongodb_minor_version != "latest"

- name: Rollback to specific MongoDB version (mongodb-org)
  apt: name=mongodb-org={{ mongodb_minor_version }} state=present force=yes
  when: mongodb_minor_version != "latest"
  register: restart_mongodb_change

- name: MongoDB Restart
  service: name=mongod state=restarted
  when: restart_mongodb_change|changed

- name: Wait for MongoDB
  wait_for: port=27017
